Colors = {}

Colors.Classic = {
    {id = 0, name = "BLACK",},
    {id = 1, name = "GRAPHITE",},
    {id = 2, name = "BLACK_STEEL",},
    {id = 3, name = "DARK_SILVER",},
    {id = 4, name = "SILVER",},
    {id = 5, name = "BLUE_SILVER",},
    {id = 6, name = "ROLLED_STEEL",},
    {id = 7, name = "SHADOW_SILVER",},
    {id = 8, name = "STONE_SILVER",},
    {id = 9, name = "MIDNIGHT_SILVER",},
    {id = 10, name = "CAST_IRON_SIL",},
    {id = 11, name = "ANTHR_BLACK",},
    {id = 27, name = "RED",},
    {id = 28, name = "TORINO_RED",},
    {id = 29, name = "FORMULA_RED",},
    {id = 30, name = "BLAZE_RED",},
    {id = 31, name = "GRACE_RED",},
    {id = 32, name = "GARNET_RED",},
    {id = 33, name = "SUNSET_RED",},
    {id = 34, name = "CABERNET_RED",},
    {id = 35, name = "CANDY_RED",},
    {id = 36, name = "SUNRISE_ORANGE",},
    {id = 37, name = "GOLD",},
    {id = 38, name = "ORANGE",},
    {id = 49, name = "DARK_GREEN",},
    {id = 50, name = "RACING_GREEN",},
    {id = 51, name = "SEA_GREEN",},
    {id = 52, name = "OLIVE_GREEN",},
    {id = 53, name = "BRIGHT_GREEN",},
    {id = 54, name = "PETROL_GREEN",},
    {id = 61, name = "GALAXY_BLUE",},
    {id = 62, name = "DARK_BLUE",},
    {id = 63, name = "SAXON_BLUE",},
    {id = 64, name = "BLUE",},
    {id = 65, name = "MARINER_BLUE",},
    {id = 66, name = "HARBOR_BLUE",},
    {id = 67, name = "DIAMOND_BLUE",},
    {id = 68, name = "SURF_BLUE",},
    {id = 69, name = "NAUTICAL_BLUE",},
    {id = 70, name = "ULTRA_BLUE",},
    {id = 71, name = "PURPLE",},
    {id = 72, name = "SPIN_PURPLE",},
    {id = 73, name = "RACING_BLUE",},
    {id = 74, name = "LIGHT_BLUE",},
    {id = 88, name = "YELLOW",},
    {id = 89, name = "RACE_YELLOW",},
    {id = 90, name = "BRONZE",},
    {id = 91, name = "FLUR_YELLOW",},
    {id = 92, name = "LIME_GREEN",},
    {id = 94, name = "UMBER_BROWN",},
    {id = 95, name = "CREEK_BROWN",},
    {id = 96, name = "CHOCOLATE_BROWN",},
    {id = 97, name = "MAPLE_BROWN",},
    {id = 98, name = "SADDLE_BROWN",},
    {id = 99, name = "STRAW_BROWN",},
    {id = 100, name = "MOSS_BROWN",},
    {id = 101, name = "BISON_BROWN",},
    {id = 102, name = "WOODBEECH_BROWN",},
    {id = 103, name = "BEECHWOOD_BROWN",},
    {id = 104, name = "SIENNA_BROWN",},
    {id = 105, name = "SANDY_BROWN",},
    {id = 106, name = "BLEECHED_BROWN",},
    {id = 107, name = "CREAM",},
    {id = 111, name = "WHITE",},
    {id = 112, name = "FROST_WHITE",},
    {id = 135, name = "HOT PINK",},
    {id = 136, name = "SALMON_PINK",},
    {id = 137, name = "PINK",},
    {id = 138, name = "BRIGHT_ORANGE",},
    {id = 141, name = "MIDNIGHT_BLUE",},
    {id = 142, name = "MIGHT_PURPLE",},
    {id = 143, name = "WINE_RED",},
    {id = 145, name = "BRIGHT_PURPLE",},
    {id = 146, name = "VERY_DARK_BLUE",},
    {id = 147, name = "BLACK_GRAPHITE",},
    {id = 150, name = "LAVA_RED",},
}

Colors.Matte = {
    { id = 12, name = "BLACK",},
    { id = 13, name = "GREY",},
    { id = 14, name = "LIGHT_GREY",},
    { id = 39, name = "RED",},
    { id = 40, name = "DARK_RED",},
    { id = 41, name = "ORANGE",},
    { id = 42, name = "YELLOW",},
    { id = 55, name = "LIME_GREEN",},
    { id = 82, name = "DARK_BLUE",},
    { id = 83, name = "BLUE",},
    { id = 84, name = "MIDNIGHT_BLUE",},
    { id = 128, name = "GREEN",},
    { id = 148, name = "Purple",},
    { id = 149, name = "MIGHT_PURPLE",},
    { id = 151, name = "MATTE_FOR",},
    { id = 152, name = "MATTE_OD",},
    { id = 153, name = "MATTE_DIRT",},
    { id = 154, name = "MATTE_DESERT",},
    { id = 155, name = "MATTE_FOIL",},
}

Colors.Metal = {
    { id = 117, name = "BR_STEEL",},
    { id = 118, name = "BR BLACK_STEEL",},
    { id = 119, name = "BR_ALUMINIUM",},
    { id = 158, name = "GOLD_P",},
    { id = 159, name = "GOLD_S",},
}

Colors.Util = {
    { id = 15, name = "BLACK",},
    { id = 16, name = "FMMC_COL1_1",},
    { id = 17, name = "DARK_SILVER",},
    { id = 18, name = "SILVER",},
    { id = 19, name = "BLACK_STEEL",},
    { id = 20, name = "SHADOW_SILVER",},
    { id = 43, name = "DARK_RED",},
    { id = 44, name = "RED",},
    { id = 45, name = "GARNET_RED",},
    { id = 56, name = "DARK_GREEN",},
    { id = 57, name = "GREEN",},
    { id = 75, name = "DARK_BLUE",},
    { id = 76, name = "MIDNIGHT_BLUE",},
    { id = 77, name = "SAXON_BLUE",},
    { id = 78, name = "NAUTICAL_BLUE",},
    { id = 79, name = "BLUE",},
    { id = 80, name = "FMMC_COL1_13",},
    { id = 81, name = "BRIGHT_PURPLE",},
    { id = 93, name = "STRAW_BROWN",},
    { id = 108, name = "UMBER_BROWN",},
    { id = 109, name = "MOSS_BROWN",},
    { id = 110, name = "SANDY_BROWN",},
    { id = 122, name = "veh_color_off_white",},
    { id = 125, name = "BRIGHT_GREEN",},
    { id = 127, name = "HARBOR_BLUE",},
    { id = 134, name = "FROST_WHITE",},
    { id = 139, name = "LIME_GREEN",},
    { id = 140, name = "ULTRA_BLUE",},
    { id = 144, name = "GREY",},
    { id = 157, name = "LIGHT_BLUE",},
    { id = 160, name = "YELLOW",},
}

Colors.Worn = {
    { id = 21, name = "BLACK",},
    { id = 22, name = "GRAPHITE",},
    { id = 23, name = "LIGHT_GREY",},
    { id = 24, name = "SILVER",},
    { id = 25, name = "BLUE_SILVER",},
    { id = 26, name = "SHADOW_SILVER",},
    { id = 46, name = "RED",},
    { id = 47, name = "SALMON_PINK",},
    { id = 48, name = "DARK_RED",},
    { id = 58, name = "DARK_GREEN",},
    { id = 59, name = "GREEN",},
    { id = 60, name = "SEA_GREEN",},
    { id = 85, name = "DARK_BLUE",},
    { id = 86, name = "BLUE",},
    { id = 87, name = "LIGHT_BLUE",},
    { id = 113, name = "SANDY_BROWN",},
    { id = 114, name = "BISON_BROWN",},
    { id = 115, name = "CREEK_BROWN",},
    { id = 116, name = "BLEECHED_BROWN",},
    { id = 121, name = "veh_color_off_white",},
    { id = 123, name = "ORANGE",},
    { id = 124, name = "SUNRISE_ORANGE",},
    { id = 126, name = "veh_color_taxi_yellow",},
    { id = 129, name = "RACING_GREEN",},
    { id = 130, name = "ORANGE",},
    { id = 131, name = "WHITE",},
    { id = 132, name = "FROST_WHITE",},
    { id = 133, name = "OLIVE_GREEN",},
}

Colors.Underglow = {
    {  255, 255, 255  },   -- White
    {  2, 21, 255  },      -- Blue
    {  3, 83, 255  },      -- Electric blue
    {  0, 255, 140  },     -- Mint Green
    {  94, 255, 1  },      -- Lime Green
    {  255, 255, 0  },     -- Yellow
    {  255, 150, 5  },     -- Golden Shower
    {  255, 62, 0  },      -- Orange
    {  255, 0, 0  },       -- Red
    {  255, 50, 100  },    -- Pony Pink
    {  255, 5, 190  },     -- Hot Pink
    {  35, 1, 255  },      -- Purple
    {  15, 3, 255  },      -- Blacklight
}